= Conditions

*Conditions* are a substitute for consequences, and replace them
entirely. Conditions serve two purposes: they take some of the pressure
off of the players and GM to quickly figure out a correctly-worded
aspect for an inflicted consequence, and they give you an opportunity to
shape the nature of your game by pre-defining the ways lasting harm
befalls characters.

The _Fate Condensed_ version of conditions takes each consequence level
and splits it into two conditions of half the value.

*[1]* *Hurt* (Mild) *[1]* *Scared* (Mild) +
*[2]* *Injured* (Moderate) *[2]* *Shaken* (Moderate) +
*[3]* *Wounded* (Severe) *[3]* *Demoralized* (Severe)

These correspond to physical and mental states—but just because you’ve
taken a physical hit doesn’t mean you can’t also mark a mental
condition, and vice-versa, so long as it makes sense. Attacks are
traumatic!

Conditions are recovered just like consequences, based on their
severity.

If you would gain an additional mild consequence, instead gain two more
boxes on either *Hurt* or *Scared*, as appropriate.

== Moving Conditions Further Apart

If you would prefer instead to keep physical and mental conditions
separate, double the number of boxes on each. That said, there is a
cutoff: if two boxes total are marked on either condition in a row, no
more boxes may be marked on that row. So if you had one box (out of two)
marked on *Hurt* and none on *Scared*, and then marked either the second
*Hurt* box or first *Scared* box, you would no longer be able to mark
any more boxes on that row.

If you would gain a mild consequence slot (from high Physique, Will, or
a stunt), instead add two more boxes of *Hurt* or *Scared* as
appropriate. These added boxes increase the cutoff threshold for that
row, one for one.

== Other Versions of Conditions

Several published Fate-based games use conditions instead of
consequences. Feel free to adopt their implementation instead of this
one if it better suits you. Each one achieves much the same purpose for
the game: reducing pressure to figure out consequence aspects on the
fly, and guiding the nature of the game by limiting the kinds of lasting
harm characters can take.
