= Credits

.Asciidoctor layout
- Chris L. Barnes

.https://github.com/amazingrando/fate-srd-content[Standardized FATE SRD HTML files]
- Randy Oest, aka https://randyoest.com[Amazing Rando]
- John Alan Large, aka https://reddicediaries.com/[Red Dice Diaries]

== Fate

Fate Condensed by PK Sullivan, Ed Turner, and Fred Hicks. Additional
development by Richard Bellingham, Robert Hanz, and Sophie Lagacé.

Based on prior works by Rob Donoghue, Fred Hicks, Leonard Balsera, Ryan
Macklin, Clark Valentine, Mike Olson, Brian Engard, and Sophie Lagacé.

Based on Fate Core System by Leonard Balsera, Brian Engard, Jeremy
Keller, Ryan Macklin, and Mike Olson and Fate Accelerated Edition by
Clark Valentine.

Turn order system based on “Accidentally Designing Marvel’s Action Order
System,” written by Fred Hicks and describing a variation on a method
originally devised by Leonard Balsera.

Portions of this work are based on Fateful Concepts: Hacking Contests by
Ryan Macklin, licensed for our use under the Creative Commons
Attribution 3.0 Unported license.
