= Changing the Skill List

As mentioned on *page XX* skill lists are the first thing to consider
tinkering with when making your own Fate game. Our default skill setup
presents a list of 19 skills arranged in a pyramid of 10. That list is
also structured around a traditional notion of capabilities in various
fields of action, in essence addressing the question “what can you do?”
Other skill lists aren’t necessarily the same length, arranged the same
way, or addressing the same question. With that said, here are some
short skill lists to consider, borrow, and modify.

* *Actions:* Endure, Fight, Know, Move, Notice, Pilot, Sneak, Speak,
Tinker.
* *Approaches:* Careful, Clever, Flashy, Forceful, Quick, Sneaky.
* *Aptitudes:* Athletics, Combat, Leadership, Scholarship, Subterfuge.
* *Attributes:* Strength, Dexterity, Toughness, Intelligence, Charm.
* *Relationships:* Leading, Partnering, Supporting, Solo.
* *Roles:* Driver, Hitter, Hacker, Gearhead, Grifter, Thief, Mastermind.
* *Themes:* Air, Fire, Metal, Mind, Stone, Void, Water, Wind, Wood.
* *Values:* Duty, Glory, Justice, Love, Power, Safety, Truth, Vengeance.

If you want a longer list, try starting with the default list, adding,
combining, and removing skills from it as needed until you land on what
you’re after. You could instead blend together two or more lists from
the above in some form.

*Advancement:* The smaller the number of skills in your list vs. the
default, the less frequent you’ll want skill point awards from
advancement. Perhaps allow them only during “power ups” (*page XX*), or
restrict them another way.

*Alternatives to the pyramid:*

* *Diamond:* A broad middle (about a third of them) that tapers towards
the top and bottom of the range, _e.g.,_ 1 at +0, 2 at +1, 3 at +2, 2 at
+3, 1 at +4.
* *Column:* A roughly equal number of skills rated at each tier. If your
list is short enough, this might be a line, one skill per tier.
* *Free + Cap:* Give players enough skill points to make a pyramid (or
other shape), but don’t mandate it. They can buy whatever, staying under
the cap.

*Coverage:* Make sure to consider how many skills you expect to be rated
out of the total. The default list has ratings in 53% (10 of 19). The
higher the percentage, the more overlap players might have. Preserve
niche protection.

*Combination:* You may want to have two lists, with players adding
together one from each to make their roll. The main thing to keep in
mind is keeping the potential totals inside the zero-to-cap range. You
might have ratings from +0 to +2 on each list, or -1 to +1 on one and +1
to +3 on the other, etc.
