= Countdowns

A countdown adds urgency to an adversary or situation: deal with it now
or things will get worse. Whether you’re talking about a ticking bomb, a
ritual near completion, a bus teetering on the edge of a suspension
bridge, or a soldier with a radio who’s about to call in reinforcements,
countdowns force the PCs to act quickly or face a worse outcome.

Countdowns have three components: a countdown track, one or more
triggers, and an outcome.

The *countdown track* looks a lot like a stress track: it’s a row of
boxes that you mark from left to right. Every time you check off a box,
the countdown gets closer to being over. The shorter the track, the
faster their doom approaches.

A *trigger* is an event that marks a box on the countdown track. It can
be as simple as “a minute/hour/day/exchange elapses” or as specific as
“the villain takes a consequence or gets taken out.”

When you mark the last box, the countdown ends and the *outcome*
happens, whatever it is.

GMs might wish to reveal the existence of a countdown track to players
without telling them what it represents, at first, as a kind of
foreshadowing and to turn up the feeling of tension in the story.

A countdown can have more than one trigger if you want; perhaps the
countdown proceeds at a predictable pace until something happens that
accelerates it. You could also give a different trigger to each box on
the countdown track, if you want a specific series of events to set off
the outcome.
