= Obstacles

The defining quality of enemies is that they can be attacked and taken
out. By contrast, the defining quality of *obstacles* is that they
can’t. Obstacles make scenes demonstrably more difficult on the PCs, but
the PCs cannot simply fight them. Obstacles must be circumvented,
endured, or rendered irrelevant.

While most obstacles are features of the environment, some might be
characters that can’t be taken out using conventional methods. The
dragon might be a boss, but it might just as easily be a hazard
obstacle. The animate statue keeping you from getting to the evil wizard
might be a threat, but it could also be a block or a distraction. It all
depends on the adversary’s function in the scene, and how PCs must deal
with it.

Obstacles don’t appear in every scene. They serve to accent enemies in
the scene, to make them more threatening or memorable, but overuse of
obstacles can be frustrating to the PCs, particularly those focused on
combat. You _can_ use them to give less combative PCs something to do
during a fight, though.

There are three kinds of obstacles: hazards, blocks, and distactions.

== Hazards

If an obstacle can attack the PCs, it’s a *hazard*. Fire jets, rolling
boulders, or a sniper too far away to be dealt with directly—they’re all
hazards. Every hazard has a name, a skill rating, and a Weapon rating
(*page XX*) of 1 to 4.

The hazard’s name is both a skill and an aspect; that is, the name
defines what the hazard can do, and its skill rating defines how good it
is at doing that, but the name can also be invoked or compelled like any
aspect.

Generally speaking, a hazard’s skill rating should be at least as high
as the PCs’ highest skill rating, if not a little bit higher. A hazard
with a very high skill rating _and_ a very high Weapon rating will
likely take out a PC or two. You could also make a hazard with a lower
skill rating but a high Weapon rating, making for something that doesn’t
hit often but hits hard when it does. Reversing that makes a hazard that
hits frequently but doesn’t do much damage.

A hazard acts in the initiative just like the PCs and their enemies do.
If your rules require everyone to roll for initiative, hazards will roll
with their rating. On its turn each exchange, a hazard acts as implied
by its name, and rolls with its rating. If it attacks and succeeds, add
its Weapon rating to its shifts. Hazards can attack or create
advantages; they can’t be attacked, and they don’t overcome obstacles.

If a player wants to overcome or create an advantage against a hazard,
they’ll face passive opposition equal to the hazard’s rating.

== Blocks

Where hazards exist to hurt the PCs, *blocks* prevent them from doing
things they want to do. Blocks _can_ cause stress, though they don’t
always. The chief differences between blocks and hazards is that blocks
don’t take actions and are more difficult to remove. Blocks provide
passive opposition in certain circumstances, and can threaten or cause
harm if not heeded.

Like hazards, blocks have a name and a skill rating, and the name is
both a skill and an aspect. Unlike hazards, a block’s skill rating
shouldn’t be much higher than one step above the PCs’ highest skill
rating; otherwise, things can get frustrating quickly. A block can have
a Weapon rating as high as 4, but it doesn’t need to have one.

Blocks only come into play under specific circumstances. A *Vat of Acid*
only matters when someone tries to cross it or gets thrown into it. A
*Chain Link Fence* only affects someone who tries to get past it. The
*Animate Statue* only prevents entry into a specific room.

Blocks don’t attack and don’t have a turn in the initiative order.
Instead, whenever a block would interfere with someone’s action, they’ll
have to roll against the block’s rating as a set difficulty. If the
block can’t cause harm, it simply prevents the PC from taking the action
they wanted to. If it can cause harm and the PC fails to overcome the
block, the PC takes a hit equal to the amount by which they missed the
target.

Characters may try to force someone into a block as an attack. If you do
this, you’ll roll to attack as normal, but add a Weapon rating equal to
half the block’s Weapon rating (rounded down, minimum 1).

Finally, some blocks can be used as cover or as armor. This is
situational—for some blocks, it simply won’t make sense. You probably
can’t hide behind a *Vat of Acid*, but a *Chain Link Fence* _is_
effective protection against a baseball bat, probably preventing the
attack altogether.

When someone’s using a block as cover, decide whether it mitigates or
negates the attack. If it negates it, the attack simply isn’t possible.
If it mitigates it, the defender gets an Armor rating equal to half the
block’s skill rating (rounded down, minimum 1).

Use blocks sparingly. Blocks make it harder for PCs to take certain
actions—so they can be frustrating if you overuse them—but they can also
lead the players to think creatively. They may see an opportunity to
turn blocks to their advantage. If they figure out how, let them!

Sometimes players will just want to remove blocks outright. To do so,
make an overcome roll against a set difficulty equal to the block’s
rating plus two.

== Distractions

Where hazards attack the PCs directly and blocks prevent them from
taking certain actions, *distractions* force the PCs to figure out their
priorities. Of the obstacles, distractions are often the least
mechanically defined. They also don’t necessarily make the scene
mechanically harder. Rather, they present the PCs with difficult
decisions. Here are the distraction’s parts:

* A distraction’s *name* is a brief, punchy representation of what it
is. It can be an aspect, if you need or want it to be.
* A distraction’s *choice* is a simple question that codifies the
decision it gives to the PCs.
* A distraction’s *repercussion* is what happens to the PCs if they
don’t deal with the distraction. Some distractions might have multiple
repercussions, including repercussions for _successfully_ dealing with
the distraction.
* A distraction’s *opposition* is its passive opposition against PCs
rolling to deal with it. Not every distraction needs to provide
opposition.

If you’re afraid the PCs will deal handily with a fight you’ve got in
store, adding a distraction or two can force them to decide whether it’s
more important to trounce the bad guys or deal with the distractions.

Dealing with a distraction should always have a clear benefit or,
failing that, not dealing with a distraction should always have a clear
consequence.

Examples of Obstacles

Hazards

* Great (+4) *Machine-Gun Turret*, Weapon:3
* Superb (+5) *Distant Sniper*, Weapon:4

Blocks

* Fair (+2) *Chain Link Fence* , Great (+4) difficulty to remove
* Good (+3) *Vat of Acid*, Weapon:4, Superb (+5) difficulty to remove

Distractions

* **Bus Full of Civilians—****Choice: *_Will the bus plunge off the
bridge?_* Opposition: *Good (+3)* Repercussion (leave them): *All of the
civilians on the bus die.* Repercussion (save them):** The villain gets
away!
* **The Glittering Gem—****Choice: *_Can you take the gem from the
pedestal?_* Repercussion (leave the gem): *You don’t get the (priceless)
gem.* Repercussion (take the gem):** You activate the traps in the
temple.
