= Scale

*Scale* is an optional subsystem that you can use to represent
supernatural beings which operate on a level beyond the general range of
capabilities of most characters in your game. Usually you don’t need to
worry about the impact of scale within your game. There may be times,
however, where it’s desirable to present the characters with a threat
bigger than they typically face—or an opportunity for the characters to
punch outside their usual weight class.

As an example—you may wish to change the list to something more suitable
to your setting—we’ll present you with five potential levels of scale:
Mundane, Supernatural, Otherworldly, Legendary, and Godlike.

* *Mundane* represents characters without access to supernatural power
or technologies that would boost them beyond the capabilities of humans.
* *Supernatural* represents characters who do have access to
supernatural powers or technologies reaching beyond human capacity but
who are still effectively human at the core.
* *Otherworldly* represents unusual or unique characters whose powers
set them apart from the normal concerns of humanity.
* *Legendary* represents powerful spirits, entities, and alien beings to
whom humanity is more of a curiosity than a threat.
* *Godlike* represents the universe’s mightiest forces: archangels,
gods, faerie queens, living planets, and so on.

When applying scale to two opposing forces or individuals, compare the
sides’ levels and determine who is higher, and by how many levels. They
get _one_ of the following benefits on any rolled action against their
lesser:

* +1 per level of difference to their action _before_ the roll
* +2 per level of difference to the result _after_ the roll, _if_ the
roll succeeds
* 1 additional free invoke per level of difference to the results of a
successful create advantage action

Frequent and rigid application of scale rules may put player characters
at a distinct disadvantage. Compensate by generously affording those
players opportunities to subvert scale disadvantage in clever ways.
Viable options include researching a target for weaknesses, changing the
venue to one where scale doesn’t apply, or altering goals so that their
opponent cannot leverage their scale advantage.

== Aspects and Scale

[#_idTextAnchor028]####Active situation aspects sometimes represent a
supernatural effect. In these cases, the GM may determine that invoking
the aspect grants the additional benefit of its scale. Furthermore, a
supernaturally created aspect can justify scale on some actions even
without an invoke, such as in the case of a veil or high-tech camouflage
suit; you need not invoke *Veiled* to gain Supernatural scale when
sneaking about.

[[does-scale-apply-when-supernaturally-creating-an-advantage-]]
=== Does Scale Apply When Supernaturally Creating an Advantage?

If you are creating an advantage and _there is no opposition_, rather
than rolling you simply gain the aspect with one free invoke. That
aspect grants scale as previously described.

If you are creating the advantage _on someone else to their detriment_,
such as casting *Entangled by Animated Vines* on your foe, you may gain
scale on your effort to create the advantage.

If you are creating an advantage via supernatural means and _an opposing
party can directly impede the effort via physical or supernatural
interference,_ your scale may apply against their defend roll.

_Otherwise,_ you create the advantage without scale, but later use of
that aspect grants scale when appropriate.
