= Time Shifts

When determining how long it takes characters to do something, you may
want to use a more systematic approach to decide the impacts of success,
failure, and “at a cost” options. How much longer or faster? Let the
shifts decide, using these guidelines.

First, decide how long the task takes with a simple success. Use an
approximate quantity plus a unit of time: “a few days,” “half a minute,”
“several weeks,” and so on. Approximate quantities for use include:
half, about one, a few, or several of a given unit of time.

Then look at how many shifts the roll exceeds or misses the target by.
Each shift is worth one quantity-step from wherever your starting point
is.

So if your starting point is “a few hours,” then one shift faster jumps
the quantity down to “about one hour,” two shifts down to “half an
hour.” Going faster than “half” drops the unit down to the next smaller
(hours to minutes, etc) and quantity up to “several”, so three shifts
faster would be “several minutes.”

In the case of slower, it’s the same process in the opposite direction:
one shift slower is “several hours,” two is “half a day,” three is
“about one day.”
