= Ways to Handle Multiple Targets

Inevitably, someone at your table will want to affect multiple targets
at once. If it’s allowed, here are some methods you can use.

If you wish to be selective about your targets, you may *split shifts*.
Roll your skill, and if the resulting total is positive, you can split
that total up however you like among the targets, who each get to defend
against the shifts you assigned to them. You must assign at least one
shift to a target, or you didn’t target them at all.

Sophie faces a trio of goons and wants to strike at all three in a
flurry of thrusts with her rapier. Thanks to an invoke and a good roll,
her Fight roll comes in at Epic (+7). She assigns a Good (+3) attack to
the one that looks the most veteran, and Fair (+2) to each of the other
two, for a total of seven shifts. They each then roll to defend.

In some special circumstances, as with an explosion or similar, you may
make a *zone attack* against everyone in one zone, friend and foe alike.
Here, you don’t split shifts; every target must defend against your
total roll. The circumstances and method must be right for doing this;
often the GM will require you to invoke an aspect or use a stunt to gain
permission.

If you wish to create an advantage affecting a whole zone or group,
*target the scene* instead: place a single aspect on the zone or the
scene itself rather than placing separate aspects on each of the
targets. This has the added advantage of reducing overall book-keeping.
If someone insists on creating a separate aspect on each target, they
should be constrained to the shift splitting method.

With any of these methods, all of the targets should occupy the same
zone. The GM may allow the occasional exception due to method and
circumstance.

Only one action type should be used—such as attacking several targets in
one blow, solving two problems at once with overcome, or swaying the
minds of a few key NPCs with create an advantage. A GM might allow two
different action types under special circumstances, but those actions
should make sense for the skill used by both.
