= Ways to Break the Rules for Big Bads

Between combining skills and creating advantages for teamwork (*page
XX*), a group of PCs can really overwhelm a single opponent. This is
fine if you want to respect the advantage of numbers, but not great if
you want to present a “big bad” that’s the equal of the whole group.

But remember, for monsters and other big threats it’s acceptable to
break the rules (*page XX*)—so do so by looking at ways to counteract
the group’s usual advantage of numbers, while still giving them a
chance. Here are a few suggestions for ways you might do that. You can
use one or more of these in combination for especially difficult or
terrifying final bosses.

== Challenge or Contest Immunity

Both of these methods are about drawing out the final confrontation by
running the group through a clock-is-ticking-down activity before they
can actually go after the big bad directly.

With *challenge immunity*, your big bad cannot be affected directly
(mentally, physically, or both) until the group beats a challenge (e.g.,
dismantling the source of its power, figuring out what its weakness is,
etc). The big bad, meanwhile, can act freely and may attack them during
their efforts, oppose their overcome or create advantage efforts with
its defend rolls, assail their free invokes with its own overcomes, or
prepare for their eventual breakthrough by creating advantages of its
own.

With *contest immunity*, the group must win a contest to be able to
directly attack the big bad—and the big bad gets to attack them while
they’re trying. If the big bad wins the contest, it gets to pull off its
scheme and get away unscathed.

== Expendable Minion Armor

Surrounding yourself with minions is one way to try to balance a big
bad’s side against the PCs, but it only goes so far if the players can
just decide to go after the big bad directly and ignore those pesky
minions for a while.

But with *expendable minion armor* in play, a big bad may always succeed
at a cost on its defend rolls against attacks by forcing a minion into
the path of the attack. That minion doesn’t roll to defend, they just
take the hit that would have landed on the big bad otherwise. This
forces the PCs to chew through the big bad’s army before the final
confrontation.

And remember, minions don’t have to be _literal_ minions. For example,
you might write up one or more “shield generators”, each one with a
stress track and perhaps a skill for creating defensive advantages for
the shielded big bad!

== Reveal True Form

Okay, the group has thrown everything they’ve got at the big bad,
and—_awesome!_—they just took him out. There’s just one problem: that
just frees him from his cage of flesh to reveal his true form!

With *reveal true form*, your big bad isn’t just one character, it’s at
least _two_ characters which must be beaten sequentially, each one
revealing new capabilities and stunts, higher skill ratings, fresh
stress and consequence tracks, and even new “rule breaks.”

If you want to gentle this a bit, carry the consequences the big bad has
already taken forward between forms, dismissing the mild ones and
downgrading the moderate and severe ones by one step each.

== Scale Things Up

You could *scale things up* to let your big bad operate at a higher
scale than the PCs, using the scale option from *page XX*. You could do
this even if scale isn’t normally in play in your campaign—these rules
need only apply when a big bad takes the field!

== Solo Bonus

Players may enjoy a teamwork bonus, sure—but why not give your big bad a
complementary *solo bonus* when they’re the only one facing the heroes?

There are a few ways you could implement a solo bonus. You could use
more than one of these, but be careful when combining them as they’ll
add up fast.

* The big bad gets a *bonus to skill rolls* that’s equal to the group’s
maximum potential teamwork bonus (*page XX*) — the number of PCs acting
against the big bad minus one (so a +2 vs a group of 3, etc). This bonus
can’t do better than double the big bad’s affected skill, though, just
as with PCs (or maybe you’ll break _that_rule too).
* The big bad may *reduce the stress* of successful attacks by the
number of opposing PCs divided by two, rounded up. If you’re worried
this will make the fight run too long, then hits reduced this way can’t
be reduced below 1.
* The big bad has *amplified invokes*: when making a _paid_ invoke of an
aspect, their bonus is equal to the number of PCs they face. No such
luck with free invokes, but this makes every fate point spent utterly
terrifying.
* The big bad may *suppress invokes*: when facing two or more foes, the
opposition’s invokes only provide a +1 bonus, or allow rerolls only,
when used directly against the big bad. Optionally, the big bad might
also remove the PCs’ ability to stack free invokes.

[[the-threat-is-a-map-or-a-hive-of-characters-]]
== The Threat is a Map (or a Hive of Characters)

In Fate, anything can be a character, so why not a map? When *the threat
is a map*, your big bad has zones (*page XX*) which must be navigated to
achieve victory.

As you detail your big bad map, each zone might have its own skills,
aspects, and stress capacity. Some zones might contain simple challenges
that must be overcome in order to move deeper into the creature. Each
zone may take an action as a separate character against PCs occupying
that zone, or in the case of a zone representing a limb or similar, may
be able to attack adjacent zones as well. If a zone is taken out by one
of the PC’s attacks, it may be bypassed and no longer gets to take
actions of its own, but the overall big bad isn’t defeated until the
heroes can reach its heart and kill it true.

This method works particularly well if your big bad is a truly gigantic
monster, but need not be limited to that situation. You can use the idea
of treating the threat as a collection of interconnected characters,
without requiring that the PCs actually enter or navigate the big bad as
a literal map. Used this way, you’ve got a hybrid between a map and
expendable minion armor (*page XX*)—a *hive of characters*, after a
fashion. Some parts of the big bad must be defeated before the players
can hit where it is truly vulnerable, and those parts get to take their
own actions in the exchange.

Whether you fully engage the map idea or simply build the big bad as a
hive, you’re sure to end up with a more dynamic fight where the big bad
acts more frequently, and the players must figure out a plan of attack
that eliminates the threat piece by piece before they can finally put it
down.
